import "../globals.css";
import SidebarComponent from "@/components/SidebarComponent";
import { Rubik } from "next/font/google";
import SearchbarComponent from "@/components/SearchbarComponent";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const rubik = Rubik({ subsets: ["latin"], variable: "--font-rubik" });

export default function RootLayout({ children }) {
  return (
      <div className={`${rubik.className} antialiased`}>
        <div className="flex">
          <SidebarComponent/>
          <div className="flex flex-col w-full px-10 pt-5 bg-blue-50 gap-5">
            <SearchbarComponent/>
            {children}
          </div>
        </div>
      </div>
  );
}
